import 'sweet_model.dart';

/// Sample sweet products for the Sweet Mart app.
final List<Sweet> dummySweetsData = [
  Sweet(
    id: '1',
    name: 'Gulab Jamun',
    price: 149.0,
    imageUrl: 'assets/images/gluabjamun.jpeg',
    description: 'Soft and juicy Indian sweet balls dipped in sugar syrup.',
    rating: 4.9,
    reviewCount: 245,
  ),
  Sweet(
    id: '2',
    name: 'Jalebi',
    price: 129.0,
    imageUrl: 'assets/images/Jalebi.jpeg',
    description: 'Crispy spiral sweets soaked in saffron syrup.',
    rating: 4.8,
    reviewCount: 218,
  ),
  Sweet(
    id: '3',
    name: 'Rasgulla',
    price: 179.0,
    imageUrl: 'assets/images/Rasgulla.jpeg',
    description: 'Soft cheese balls soaked in light sugar syrup.',
    rating: 4.7,
    reviewCount: 174,
  ),
  Sweet(
    id: '4',
    name: 'Laddu',
    price: 109.0,
    imageUrl: 'assets/images/laddu.jpeg',
    description: 'Traditional round sweets made with ghee and flour.',
    rating: 4.7,
    reviewCount: 190,
  ),
  Sweet(
    id: '5',
    name: 'Kaju Katli',
    price: 249.0,
    imageUrl: 'assets/images/Kajukatli.jpeg',
    description: 'Premium cashew fudge with silver coating.',
    rating: 4.8,
    reviewCount: 206,
  ),
  Sweet(
    id: '6',
    name: 'Barfi',
    price: 159.0,
    imageUrl: 'assets/images/Berfi.jpeg',
    description: 'Classic milk-based sweet with rich flavor.',
    rating: 4.6,
    reviewCount: 156,
  ),
  Sweet(
    id: '7',
    name: 'Motichoor Laddu',
    price: 189.0,
    imageUrl: 'assets/images/laddu.jpeg',
    description: 'Tiny boondi pearls shaped into rich festive laddus.',
    rating: 4.7,
    reviewCount: 128,
  ),
  Sweet(
    id: '8',
    name: 'Besan Laddu',
    price: 169.0,
    imageUrl: 'assets/images/laddu.jpeg',
    description: 'Aromatic gram flour laddus roasted in ghee for bulk gifting.',
    rating: 4.6,
    reviewCount: 96,
  ),
  Sweet(
    id: '9',
    name: 'Soan Papdi',
    price: 139.0,
    imageUrl: 'assets/images/Berfi.jpeg',
    description:
        'Flaky cube sweets often ordered for festivals and office boxes.',
    rating: 4.4,
    reviewCount: 84,
  ),
  Sweet(
    id: '10',
    name: 'Mysore Pak',
    price: 219.0,
    imageUrl: 'assets/images/Berfi.jpeg',
    description: 'Rich ghee and gram flour sweet with a melt-in-mouth texture.',
    rating: 4.8,
    reviewCount: 112,
  ),
  Sweet(
    id: '11',
    name: 'Peda',
    price: 179.0,
    imageUrl: 'assets/images/Berfi.jpeg',
    description:
        'Soft milk peda, a popular choice for prasad and celebrations.',
    rating: 4.6,
    reviewCount: 101,
  ),
  Sweet(
    id: '12',
    name: 'Milk Cake',
    price: 229.0,
    imageUrl: 'assets/images/Berfi.jpeg',
    description: 'Grainy caramelized milk sweet packed well for large orders.',
    rating: 4.7,
    reviewCount: 89,
  ),
  Sweet(
    id: '13',
    name: 'Dry Fruit Barfi',
    price: 299.0,
    imageUrl: 'assets/images/Kajukatli.jpeg',
    description: 'Premium dry fruit barfi for wedding and corporate gifting.',
    rating: 4.8,
    reviewCount: 76,
  ),
  Sweet(
    id: '14',
    name: 'Kalakand',
    price: 239.0,
    imageUrl: 'assets/images/Berfi.jpeg',
    description: 'Moist milk cake sweet topped with nuts for festive trays.',
    rating: 4.6,
    reviewCount: 73,
  ),
  Sweet(
    id: '15',
    name: 'Cham Cham',
    price: 199.0,
    imageUrl: 'assets/images/Rasgulla.jpeg',
    description: 'Spongy Bengali sweet commonly ordered for family functions.',
    rating: 4.5,
    reviewCount: 68,
  ),
  Sweet(
    id: '16',
    name: 'Imarti',
    price: 149.0,
    imageUrl: 'assets/images/Jalebi.jpeg',
    description: 'Crisp syrup-soaked sweet, ideal for fresh bulk party orders.',
    rating: 4.5,
    reviewCount: 82,
  ),
];
